---
version: 2.1

orbs:
  do: twdps/pipeline-events@5.0.1

globals:
  - &context platform
  - &executor-image twdps/circleci-infra-aws:alpine-stable

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

jobs:

  write-global-values-to-op:
    docker:
      - image: *executor-image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: write gobal values to platform vault
          command: bash scripts/write_key_values_to_op.sh

  recurring-drift-check:
    docker:
      - image: *executor-image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: compare global_values with settings in op
          command: bash scripts/compare_op_with_desired_values.sh

workflows:
  version: 2

  store global values in vault:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - write-global-values-to-op:
          context: *context
          filters: *on-push-main

      - do/schedule-pipeline:
          name: schedule nightly drift check
          context: *context
          shell: op run --env-file op.env -- /bin/bash -eo pipefail
          scheduled-pipeline-name: nightly-drift-check
          scheduled-pipeline-description: |
            Nightly, automated comparison of desired values with values in op. Difference indicates changes made directly in op.
          hours-of-day: "[1]"
          days-of-week: "[\"SUN\", \"MON\",\"TUE\",\"WED\",\"THU\"]"
          filters: *on-push-main

  nightly drift check:
    when:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - recurring-drift-check:
          context: *context
